import Field from "./Field";
import RichTextEditor from "./RichTextEditor";

const habitats = ["Planícies", "Colinas", "Montanhas", "Pântanos", "Geleiras", "Desertos", "Florestas", "Subterrâneos", "Oceanos", "Extra planar"];

export default function EntryEditor({ entry, onChange }) {
  const update = (key, value) => onChange({ ...entry, [key]: value });
  const attackUpdate = (i, key, value) => update("attacks", entry.attacks.map((a, n) => n === i ? { ...a, [key]: value } : a));
  const listUpdate = (listKey, i, key, value) => update(listKey, (entry[listKey] || []).map((item, n) => n === i ? { ...item, [key]: value } : item));
  const isMonster = entry.type === "monstros";
  const isRace = entry.type === "racas", isClass = entry.type === "classes", isGear = entry.type === "equipamentos", isSpell = entry.type === "magias";
  return <div className="editor-scroll">
    <section className="editor-section basic-section">
      <div className="section-heading"><div><span className="eyebrow">01 / IDENTIDADE</span><h2>Informações básicas</h2><p>Comece pelo que define sua criação.</p></div><span className="section-symbol">✳</span></div>
      <div className="form-grid basic-grid">
        <Field label="Nome" help="Como sua criação é chamada."><input autoFocus placeholder="Ex.: Brugo ou Bufante" value={entry.name} onChange={e => update("name", e.target.value)} /></Field>
        {(isRace || isClass || isSpell) && <Field label="ID para importação" help="ID estável; reutilize para atualizar o item no Foundry."><input value={entry.importId || entry.id} onChange={e => update("importId", e.target.value)} /></Field>}
        <Field label="Subtítulo" help="Uma frase curta que apresenta a ideia." className="span-two"><input placeholder="Uma frase que desperta curiosidade…" value={entry.subtitle} onChange={e => update("subtitle", e.target.value)} /></Field>
        <Field label="Imagem" help="WEBP, JPEG ou PNG • até 5 MB" className="span-three image-field">
          <div className="image-upload">
            {entry.image ? <img src={entry.image} alt="Prévia da criação" /> : <span className="image-placeholder">✧</span>}
            <div><strong>{entry.image ? "Imagem adicionada" : "Adicione uma imagem"}</strong><small>Uma imagem dá vida à sua criação.</small><label className="upload-button">Escolher arquivo<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e => { const f = e.target.files?.[0]; if (f && f.size <= 5 * 1024 * 1024) { const reader = new FileReader(); reader.onload = () => update("image", reader.result); reader.readAsDataURL(f); } }} /></label></div>
            {entry.image && <button className="text-action" onClick={() => update("image", "")}>Remover imagem</button>}
          </div>
        </Field>
      </div>
    </section>
    <section className="editor-section">
      <div className="section-heading"><div><span className="eyebrow">02 / CLASSIFICAÇÃO</span><h2>{isMonster ? "Classificação" : "Características"}</h2><p>Defina os atributos essenciais.</p></div><span className="section-symbol">◈</span></div>
      <div className="form-grid four-grid">
        <Field label="Conceito"><select value={entry.concept} onChange={e => update("concept", e.target.value)}>{["Animal", "Humanoide", "Construto", "Dragão", "Morto-vivo", "Monstro", "Planta", "Espírito"].map(x => <option key={x}>{x}</option>)}</select></Field>
        <Field label="Tamanho"><select value={entry.size} onChange={e => update("size", e.target.value)}>{["Miúdo", "Pequeno", "Médio", "Grande", "Enorme", "Gigante"].map(x => <option key={x}>{x}</option>)}</select></Field>
        <Field label={isRace ? "Tendência de alinhamento" : "Alinhamento"}><select value={entry.alignment} onChange={e => update("alignment", e.target.value)}>{["Ordeiro", "Neutro", "Caótico"].map(x => <option key={x}>{x}</option>)}</select></Field>
        <Field label="Experiência (XP)" help="Concedida ao ser derrotado."><input type="number" value={entry.xp} onChange={e => update("xp", e.target.value)} /></Field>
      </div>
      {isMonster && <div className="habitat-block"><div className="field-label">Habitats</div><span className="field-help">Onde a criatura pode ser encontrada.</span><div className="chips">{habitats.map(h => <label key={h} className={`check-chip ${(entry.habitats || []).includes(h) ? "checked" : ""}`}><input type="checkbox" checked={(entry.habitats || []).includes(h)} onChange={e => update("habitats", e.target.checked ? [...(entry.habitats || []), h] : entry.habitats.filter(x => x !== h))} /><span>{h}</span></label>)}</div></div>}
    </section>
    {(isRace || isClass || isGear || isSpell) && <section className="editor-section"><div className="section-heading"><div><span className="eyebrow">03 / DADOS DE JOGO</span><h2>{isRace ? "Traços de raça" : isClass ? "Progressão de classe" : isGear ? "Detalhes do equipamento" : "Parâmetros da magia"}</h2><p>Informações estruturadas para sua mesa.</p></div><span className="section-symbol">✧</span></div>
      <div className="form-grid three-grid">
        {isRace && <><Field label="Movimento (m)" help="Valor numérico, por exemplo 6."><input type="number" value={entry.movement || ""} onChange={e => update("movement", e.target.value)} /></Field><Field label="Infravisão (m)"><input type="number" value={entry.infravision || ""} onChange={e => update("infravision", e.target.value)} /></Field><Field label="Traços gerais"><input value={entry.raceTraits || ""} onChange={e => update("raceTraits", e.target.value)} placeholder="Características resumidas" /></Field></>}
        {isClass && <><Field label="PV por nível"><input type="number" value={entry.classHitDie || ""} onChange={e => update("classHitDie", e.target.value)} placeholder="Ex.: 8" /></Field><Field label="Bônus de PV em níveis altos"><input type="number" value={entry.highLevelHpBonus || ""} onChange={e => update("highLevelHpBonus", e.target.value)} placeholder="Ex.: 1" /></Field><Field label="BA por nível" help="Separe os valores por vírgula."><input value={entry.baProgression || ""} onChange={e => update("baProgression", e.target.value)} placeholder="1, 1, 2, 2…" /></Field><Field label="JP por nível" help="Separe os valores por vírgula."><input value={entry.jpProgression || ""} onChange={e => update("jpProgression", e.target.value)} placeholder="5, 5, 6, 6…" /></Field><Field label="XP por nível" help="Comece com 0 para o nível 1."><input value={entry.xpProgression || ""} onChange={e => update("xpProgression", e.target.value)} placeholder="0, 2000, 4000…" /></Field><Field label="Restrições de raça"><input value={entry.raceRestrictions || ""} onChange={e => update("raceRestrictions", e.target.value)} placeholder="Nomes separados por vírgula" /></Field><Field label="Restrições de alinhamento"><input value={entry.alignmentRestrictions || ""} onChange={e => update("alignmentRestrictions", e.target.value)} placeholder="Ordeiro, Neutro…" /></Field><Field label="Armas permitidas/restritas"><input value={entry.weaponRestrictions || ""} onChange={e => update("weaponRestrictions", e.target.value)} placeholder="Descrição" /></Field><Field label="Armaduras permitidas/restritas"><input value={entry.armorRestrictions || ""} onChange={e => update("armorRestrictions", e.target.value)} placeholder="Descrição" /></Field><Field label="Itens mágicos"><input value={entry.magicItemRestrictions || ""} onChange={e => update("magicItemRestrictions", e.target.value)} placeholder="Descrição" /></Field></>}
        {isGear && <><Field label="Tipo de equipamento"><input value={entry.equipmentType || ""} onChange={e => update("equipmentType", e.target.value)} placeholder="Arma, armadura, item…" /></Field><Field label="Preço"><input value={entry.price || ""} onChange={e => update("price", e.target.value)} placeholder="Ex.: 15 PO" /></Field><Field label="Peso"><input value={entry.weight || ""} onChange={e => update("weight", e.target.value)} placeholder="Ex.: 2 kg" /></Field><Field label="Dano ou proteção"><input value={entry.damage || ""} onChange={e => update("damage", e.target.value)} placeholder="Ex.: 1d8" /></Field><Field label="Propriedades"><input value={entry.properties || ""} onChange={e => update("properties", e.target.value)} placeholder="Propriedades especiais" /></Field></>}
        {isSpell && <><Field label="Círculo"><input value={entry.spellLevel || ""} onChange={e => update("spellLevel", e.target.value)} placeholder="Ex.: 1" /></Field><Field label="Escola"><select value={entry.school || "arcane"} onChange={e => update("school", e.target.value)}>{[["arcane","Arcana"],["divine","Divina"],["necromancer","Necromante"],["illusionist","Ilusionista"]].map(([v,l]) => <option key={v} value={v}>{l}</option>)}</select></Field><Field label="Alcance"><input value={entry.range || ""} onChange={e => update("range", e.target.value)} placeholder="Ex.: 18 metros" /></Field><Field label="Duração"><input value={entry.duration || ""} onChange={e => update("duration", e.target.value)} placeholder="Ex.: instantânea" /></Field><Field label="Jogada de proteção"><input value={entry.jp || ""} onChange={e => update("jp", e.target.value)} placeholder="Ex.: JPS nega" /></Field><Field label="Magia reversível"><select value={entry.reverse ? "sim" : "nao"} onChange={e => update("reverse", e.target.value === "sim")}><option value="nao">Não</option><option value="sim">Sim</option></select></Field></>}
      </div>
      {(isRace || isClass) && <div className="nested-list"><div className="nested-heading"><div><strong>{isRace ? "Habilidades raciais" : "Habilidades de classe"}</strong><small>Descrições são convertidas para parágrafos HTML na exportação.</small></div><button className="outline-button" onClick={() => update("abilities", [...(entry.abilities || []), { id: crypto.randomUUID(), name: "", description: "", ...(isClass ? { level: 1 } : {}) }])}>＋ Adicionar habilidade</button></div>
        {(entry.abilities || []).map((a, i) => <div className="ability-card" key={a.id || i}><div className="ability-top"><strong>Habilidade {i + 1}</strong><button className="remove-attack" aria-label="Remover habilidade" onClick={() => update("abilities", entry.abilities.filter((_, n) => n !== i))}>×</button></div><div className="ability-fields">{isClass && <Field label="Nível"><input type="number" min="1" value={a.level || 1} onChange={e => listUpdate("abilities", i, "level", e.target.value)} /></Field>}<Field label="Nome da habilidade"><input value={a.name} onChange={e => listUpdate("abilities", i, "name", e.target.value)} placeholder="Ex.: Foco Rúnico" /></Field><Field label="Descrição"><textarea rows={2} value={a.description} onChange={e => listUpdate("abilities", i, "description", e.target.value)} placeholder="Descreva o que a habilidade faz…" /></Field></div></div>)}
      </div>}
      {isClass && <div className="nested-list"><div className="nested-heading"><div><strong>Magias da classe</strong><small>Opcional: exportadas dentro da classe, com escola e círculo.</small></div><button className="outline-button" onClick={() => update("classSpells", [...(entry.classSpells || []), { id: crypto.randomUUID(), name: "", description: "", school: "divine", spellLevel: "1", range: "", duration: "", jp: "", reverse: false }])}>＋ Adicionar magia</button></div>
        {(entry.classSpells || []).map((s, i) => <div className="ability-card" key={s.id || i}><div className="ability-top"><strong>Magia {i + 1}</strong><button className="remove-attack" aria-label="Remover magia" onClick={() => update("classSpells", entry.classSpells.filter((_, n) => n !== i))}>×</button></div><div className="form-grid three-grid"><Field label="Nome"><input value={s.name} onChange={e => listUpdate("classSpells", i, "name", e.target.value)} /></Field><Field label="Círculo"><input value={s.spellLevel} onChange={e => listUpdate("classSpells", i, "spellLevel", e.target.value)} /></Field><Field label="Escola"><select value={s.school} onChange={e => listUpdate("classSpells", i, "school", e.target.value)}>{[["arcane","Arcana"],["divine","Divina"],["necromancer","Necromante"],["illusionist","Ilusionista"]].map(([v,l]) => <option key={v} value={v}>{l}</option>)}</select></Field><Field label="Alcance"><input value={s.range} onChange={e => listUpdate("classSpells", i, "range", e.target.value)} /></Field><Field label="Duração"><input value={s.duration} onChange={e => listUpdate("classSpells", i, "duration", e.target.value)} /></Field><Field label="JP"><input value={s.jp} onChange={e => listUpdate("classSpells", i, "jp", e.target.value)} /></Field><Field label="Descrição" className="span-three"><textarea rows={2} value={s.description} onChange={e => listUpdate("classSpells", i, "description", e.target.value)} /></Field></div></div>)}
      </div>}
    </section>}
    {isMonster && <section className="editor-section">
      <div className="section-heading"><div><span className="eyebrow">03 / COMBATE</span><h2>Atributos de combate</h2><p>Valores para colocar a criatura em jogo.</p></div><span className="section-symbol">⚔</span></div>
      <div className="form-grid three-grid">
        <Field label="Dado de Vida (DV)" help="Base para calcular os pontos de vida."><input value={entry.hd} onChange={e => update("hd", e.target.value)} /></Field>
        <Field label="Bônus no Dado de Vida"><input value={entry.hpBonus} onChange={e => update("hpBonus", e.target.value)} /></Field>
        <Field label="Pontos de Vida (PV)" help="Valor usado na ficha."><input value={entry.hp} onChange={e => update("hp", e.target.value)} /></Field>
        <Field label="Classe de Armadura (CA)"><input value={entry.ac} onChange={e => update("ac", e.target.value)} /></Field>
        <Field label="Jogada de Proteção (JP)"><input value={entry.jp} onChange={e => update("jp", e.target.value)} /></Field>
        <Field label="Moral (MO)"><input value={entry.morale} onChange={e => update("morale", e.target.value)} /></Field>
        <Field label="Movimento"><input value={entry.movement} onChange={e => update("movement", e.target.value)} /></Field>
        <Field label="Tesouro"><input value={entry.treasure} onChange={e => update("treasure", e.target.value)} /></Field>
      </div>
    </section>}
    {isMonster && <section className="editor-section">
      <div className="section-heading"><div><span className="eyebrow">04 / AÇÕES</span><h2>Ataques</h2><p>Adicione as opções de ataque da criatura.</p></div><button className="outline-button" onClick={() => update("attacks", [...entry.attacks, { count: "1", name: "", bonus: "+0", damage: "1d6", extra: "", effect: "" }])}>＋ Adicionar ataque</button></div>
      {entry.attacks.length === 0 && <div className="empty-attacks">Nenhum ataque adicionado ainda.</div>}
      {entry.attacks.map((a, i) => <div className="attack-row" key={i}><Field label="Nº de ataques"><input value={a.count} onChange={e => attackUpdate(i, "count", e.target.value)} /></Field><Field label="Tipo de ataque" className="attack-name"><input placeholder="Ex.: Mordida" value={a.name} onChange={e => attackUpdate(i, "name", e.target.value)} /></Field><Field label="BA"><input value={a.bonus} onChange={e => attackUpdate(i, "bonus", e.target.value)} /></Field><Field label="Dano"><input value={a.damage} onChange={e => attackUpdate(i, "damage", e.target.value)} /></Field><Field label="Bônus"><input value={a.extra} onChange={e => attackUpdate(i, "extra", e.target.value)} /></Field><button aria-label="Remover ataque" className="remove-attack" onClick={() => update("attacks", entry.attacks.filter((_, n) => n !== i))}>×</button></div>)}
    </section>}
    <section className="editor-section last-section"><div className="section-heading"><div><span className="eyebrow">{isMonster ? "05" : isRace || isClass || isGear || isSpell ? "04" : "03"} / NARRATIVA</span><h2>Descrição</h2><p>Organize o texto em etapas e formate como quiser.</p></div><span className="section-symbol">❧</span></div>
      <div className="description-tip"><span aria-hidden="true">ⓘ</span><p><strong>Dica:</strong> use a barra para formatar o texto: títulos, listas, citações, links, negrito, itálico e outros estilos.</p></div>
      <Field label="Descrição (Início)" help="Aparência, origem, comportamento e cultura."><RichTextEditor value={entry.description || ""} onChange={value => update("description", value)} placeholder="Descreva os detalhes que apresentam esta criação…" minHeight="180px" /></Field>
      <Field label="Descrição (Habilidades de Combate)" help="Táticas, habilidades e comportamento durante um confronto."><RichTextEditor value={entry.combat || ""} onChange={value => update("combat", value)} placeholder="Descreva como ela age quando a aventura vira confronto…" minHeight="150px" /></Field>
      <Field label="Descrição (Final)" help="Detalhes adicionais, curiosidades ou informações para fechar a descrição."><RichTextEditor value={entry.finalDescription || ""} onChange={value => update("finalDescription", value)} placeholder="Acrescente detalhes finais, ganchos ou curiosidades…" minHeight="150px" /></Field>
    </section>
  </div>;
}
